package org.sing_group.seda.io;

import static java.util.stream.Collectors.toList;

import java.io.File;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.junit.Assert;
import org.junit.Test;
import org.sing_group.seda.datatype.Sequence;

public class LazyFileMultipleSequenceAlignmentTest {
	public static final Path TEST_FILE = new File(
		"src/test/resources/fasta/test.fna").toPath();
	
	public static final String FIRST_SEQUENCE_DESCRIPTION = "[gene=NAC001] [locus_tag=AT1G01010] "
	  + "[db_xref=Araport:AT1G01010,TAIR:AT1G01010,GeneID:839580] [protein=NAC domain containing protein 1] "
	  + "[protein_id=NP_171609.1] [location=join(3760..3913,3996..4276,4486..4605,4706..5095,5174..5326,5439..5630)]";
	  
	public static final String FIRST_SEQUENCE_CHAIN = 
	  "ATGGAGGATCAAGTTGGGTTTGGGTTCCGTCCGAACGACGAGGAGCTCGTTGGTCACTATCTCCGTAACAAAATCGAAGG" + 
	  "AAACACTAGCCGCGACGTTGAAGTAGCCATCAGCGAGGTCAACATCTGTAGCTACGATCCTTGGAACTTGCGCTTCCAGT" + 
	  "CAAAGTACAAATCGAGAGATGCTATGTGGTACTTCTTCTCTCGTAGAGAAAACAACAAAGGGAATCGACAGAGCAGGACA" + 
    "ACGGTTTCTGGTAAATGGAAGCTTACCGGAGAATCTGTTGAGGTCAAGGACCAGTGGGGATTTTGTAGTGAGGGCTTTCG" + 
    "TGGTAAGATTGGTCATAAAAGGGTTTTGGTGTTCCTCGATGGAAGATACCCTGACAAAACCAAATCTGATTGGGTTATCC" + 
    "ACGAGTTCCACTACGACCTCTTACCAGAACATCAGAGGACATATGTCATCTGCAGACTTGAGTACAAGGGTGATGATGCG" + 
    "GACATTCTATCTGCTTATGCAATAGATCCCACTCCCGCTTTTGTCCCCAATATGACTAGTAGTGCAGGTTCTGTGGTCAA" + 
    "CCAATCACGTCAACGAAATTCAGGATCTTACAACACTTACTCTGAGTATGATTCAGCAAATCATGGCCAGCAGTTTAATG" + 
    "AAAACTCTAACATTATGCAGCAGCAACCACTTCAAGGATCATTCAACCCTCTCCTTGAGTATGATTTTGCAAATCACGGC" + 
    "GGTCAGTGGCTGAGTGACTATATCGACCTGCAACAGCAAGTTCCTTACTTGGCACCTTATGAAAATGAGTCGGAGATGAT" + 
    "TTGGAAGCATGTGATTGAAGAAAATTTTGAGTTTTTGGTAGATGAAAGGACATCTATGCAACAGCATTACAGTGATCACC" + 
    "GGCCCAAAAAACCTGTGTCTGGGGTTTTGCCTGATGATAGCAGTGATACTGAAACTGGATCAATGATTTTCGAAGACACT" + 
    "TCGAGCTCCACTGATAGTGTTGGTAGTTCAGATGAACCGGGCCATACTCGTATAGATGATATTCCATCATTGAACATTAT" + 
    "TGAGCCTTTGCACAATTATAAGGCACAAGAGCAACCAAAGCAGCAGAGCAAAGAAAAGGTGATAAGTTCGCAGAAAAGCG" + 
    "AATGCGAGTGGAAAATGGCTGAAGACTCGATCAAGATACCTCCATCCACCAACACGGTGAAGCAGAGCTGGATTGTTTTG" + 
    "GAGAATGCACAGTGGAACTATCTCAAGAACATGATCATTGGTGTCTTGTTGTTCATCTCCGTCATTAGTTGGATCATTCT" + 
    "TGTTGGTTAA";
	
	public static final Map<String, Object> FIRST_SEQUENCE_MAP = new HashMap<>();
	static {
	  FIRST_SEQUENCE_MAP.put(Sequence.PROPERTY_CHAIN_COLUMNS, 80);
	}
	
	private static final Sequence FIRST_SEQUENCE = Sequence.of(
	  ">lcl|NC_003070.9_cds_NP_171609.1_1", 
	  FIRST_SEQUENCE_DESCRIPTION, 
	  FIRST_SEQUENCE_CHAIN, 
	  FIRST_SEQUENCE_MAP);
	
  @Test
  public void testLoadFile() {
    List<Sequence> sequences = new LazyFileMultipleSequenceAlignment(TEST_FILE).getSequences().collect(toList());
    Assert.assertEquals(5, sequences.size());
    Assert.assertEquals(FIRST_SEQUENCE, sequences.get(0));
  }
}
